### ISSUE TITLE
Not populating colored box between April and November

### ISSUE THREAD

**Issue by mihir-chauhan** [HuanSuh/flutter_annual_task#4]
Hi @HuanSuh ,

I liked your Flutter package and started to use it, but after trying it out, I noticed how it does not populate colored boxes in the middle of the year between April and November across all types of calendars in your example project.

Screenshot:
![screenshot](https://user-images.githubusercontent.com/39073758/120868638-4a9cb300-c549-11eb-931d-cc6d561a07ee.jpg)

When I try to color a box in between this empty space, it doesn't show up. Please let me know how I can fix this. Thanks!

**Comment by HuanSuh** [comment]
Hi @mihir-chauhan,
Thanks for using this package.

It seems to work well.
In the example project, it use random generated event items with `static List<AnnualTaskItem> generateAnnualTask({int year, int sampleSize})` function.
You can test with another random generated data by refreshing (pull-to-refresh).

If it doesn't work, please tell me about details(dart/flutter/package versions, os and others) that can help me to figure it out.

Thank you.
